#!/usr/bin/env python3
"""Generate (and optionally run) a local Critic2 Fukui input from VASP preflight.

No external source vendored. Default only writes a proposed Critic2 input
under an existing work dir, with exclusive creation; original VASP input
files are never touched. --execute explicitly runs local Critic2 only.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import shutil
import subprocess
import sys

def make_input(meta,root,plus_label,minus_label):
    if meta.get("status")!="INPUT_GRID_PASS_SCF_MANUAL_CHECK":
        raise ValueError("validated VASP preflight required")
    states={s["label"]:s for s in meta["states"]}
    if len(states)!=len(meta["states"]):raise ValueError("duplicate labels in preflight")
    for name in (meta["reference"],plus_label,minus_label):
        if name not in states:raise ValueError(f"unknown preflight state {name}")
    dp=states[plus_label]["delta_electrons"]
    dm=-states[minus_label]["delta_electrons"]
    if dp<=0 or dm<=0:raise ValueError("plus/minus state signs incorrect")
    dirs=[]
    for label in (meta["reference"],plus_label,minus_label):
        rel=Path(states[label]["directory"])
        p=(root/rel).resolve()
        if not p.is_relative_to(root) or not p.is_dir():
            raise ValueError(f"unsafe / missing source state {label}")
        dirs.append(p)
    for p in [*dirs,root]:
        if any(ch.isspace() or ch in {'"',"'"} for ch in str(p)):
            raise ValueError("Critic2 input paths with whitespace/quotes need safe staging symlinks")
    n,plus,minus=dirs
    lines=[
        "# Generated by AICC periodic-cdft. Validate against LOCAL Critic2 syntax.",
        f"CRYSTAL {n/'POSCAR'}",
        f"LOAD VASP {n/'CHGCAR'} ID neutral",
        f"LOAD VASP {plus/'CHGCAR'} ID plus",
        f"LOAD VASP {minus/'CHGCAR'} ID minus",
        f'LOAD AS "($plus-$neutral)/{dp:.12g}" SIZEOF neutral ID fplus',
        f'LOAD AS "($neutral-$minus)/{dm:.12g}" SIZEOF neutral ID fminus',
        'LOAD AS "($fplus+$fminus)/2" SIZEOF neutral ID fzero',
        'LOAD AS "$fplus-$fminus" SIZEOF neutral ID dual',
    ]
    for field in ("fplus","fminus","fzero","dual"):
        lines.extend([f"SUM {field}",f"CUBE GRID FILE {field}.cube FIELD {field}"])
    lines.append("END")
    return "\n".join(lines)+"\n"

def main(argv=None):
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--root",type=Path,required=True)
    p.add_argument("--preflight",type=Path,required=True)
    p.add_argument("--plus-label",required=True)
    p.add_argument("--minus-label",required=True)
    p.add_argument("--workdir",type=Path,required=True,
                   help="Pre-existing isolated project work directory; must be empty of generated targets")
    p.add_argument("--execute",action="store_true",help="Run local Critic2 after user approval")
    p.add_argument("--critic2",default="critic2",help="Binary path/name")
    a=p.parse_args(argv)
    try:
        root=a.root.expanduser().resolve()
        work=a.workdir.expanduser().resolve()
        if not work.is_dir():raise ValueError("create an isolated workdir first")
        if not work.is_relative_to(root):
            raise ValueError("workdir must be inside VASP project root")
        dest=work/"critic2.in"
        log=work/"critic2.log"
        if dest.exists() or log.exists() or any((work/f"{x}.cube").exists()
            for x in ("fplus","fminus","fzero","dual")):
            raise ValueError("existing generated files; no overwrite")
        meta=json.loads(a.preflight.read_text(encoding="utf-8"))
        text=make_input(meta,root,a.plus_label,a.minus_label)
        with dest.open("x",encoding="utf-8") as fp:fp.write(text)
        print(f"Generated Critic2 input: {dest}")
        print(f"Invocation: cd {work} && {a.critic2} < critic2.in > critic2.log")
        if a.execute:
            binary=shutil.which(a.critic2)
            if not binary:raise ValueError("Critic2 binary not found in PATH; source input retained")
            with dest.open("r",encoding="utf-8") as inp,log.open("x",encoding="utf-8") as out:
                task=subprocess.run([binary],stdin=inp,stdout=out,stderr=subprocess.STDOUT,
                                    cwd=work,check=False)
            if task.returncode:raise ValueError(f"Critic2 exit {task.returncode}; inspect {log}")
            missing=[name for name in ("fplus","fminus","fzero","dual") if
                     not (work/f"{name}.cube").is_file()]
            if missing:raise ValueError(f"Critic2 missing outputs: {missing}; inspect {log}")
            print("Critic2 wrote four cubes; independent grid_audit.py checks still required")
        return 0
    except (ValueError,OSError,KeyError,TypeError,json.JSONDecodeError) as exc:
        print(f"CRITIC2 INPUT ERROR: {exc}",file=sys.stderr)
        return 1

if __name__=="__main__":
    sys.exit(main())
